---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: realtime-kernel-test
    box: debian/bookworm64
    memory: 1024
    cpus: 1
    networks:
      - name: 'public_network'
        type: 'dhcp'
  - name: realtime-kernel-test-existing-nomodeset
    box: debian/bookworm64
    memory: 1024
    cpus: 1
    networks:
      - name: 'public_network'
        type: 'dhcp'
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        role_name: voraus.ipc_tools.realtime_kernel
  playbooks:
    prepare: prepare.yml
    converge: ../shared/converge.yml
verifier:
  name: testinfra
  options:
    # https://github.com/pytest-dev/pytest-testinfra/issues/58#issuecomment-1839460327
    # pytest-ansible conflicts with --connection
    p: 'no:pytest-ansible'

    # avoid loading global pyproject.toml options, so we don't
    # load the setting that says "disable testinfra"
    c: '.'

    sudo: true # /boot/grub/grub.cfg is only readable by root
