---
- name: Install apt dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - gnupg2
      - curl
    state: present

- name: Clean up old wibu apt repo and GPG key
  ansible.builtin.include_tasks: cleanup_old_repo.yml

- name: Download and dearmor voraus GPG key
  ansible.builtin.shell: |
    set -o pipefail
    curl -s --compressed https://voraus.jfrog.io/ui/api/v1/ui/security/keyPairs/voraus-gpg/public | \
    gpg --dearmor -o /etc/apt/trusted.gpg.d/vorausrobotik.gpg
  args:
    executable: /bin/bash
    creates: /etc/apt/trusted.gpg.d/vorausrobotik.gpg

- name: Add voraus packages apt repo
  ansible.builtin.include_tasks: add_voraus_repo.yml

- name: Include package specific tasks
  ansible.builtin.include_tasks: 'install_{{ package_mapping[item.key] }}.yml'
  loop: '{{ wibu_packages_install | dict2items }}'
  vars:
    package_name: '{{ item.key }}'
    package_version: '{{ item.value }}'
    package_mapping:
      codemeter-lite: codemeter
      axprotector: axprotector
  when: 'item.key in package_mapping'
