- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Set fact for non-rt linux-image and linux-headers packages
  ansible.builtin.set_fact:
    realtime_kernel_non_rt_kernels: >-
      {{
        ansible_facts.packages | dict2items
        | selectattr('key', 'match', '^(linux-image-|linux-headers-)')
        | rejectattr('key', 'match', '.*rt.*')
        | map(attribute='key') | list
      }}

- name: Run install/uninstall tasks
  when: >-
    realtime_kernel_apt_packages | reject('in', ansible_facts.packages.keys()) | list | length > 0
    or
    realtime_kernel_non_rt_kernels | length > 0

  notify:
    - Update GRUB
    - Reboot Machine
  block:
    - name: Check if /boot is mounted in read-only mode
      # Returns 0 if /boot is mounted separately and in read-only mode, 1 otherwise.
      ansible.builtin.shell: grep "[[:space:]]ro[[:space:],]" /proc/mounts | grep /boot
      register: realtime_kernel_grep_boot
      ignore_errors: true
      changed_when: false

    - name: Remount /boot partition in read-write mode if necessary
      ansible.posix.mount:
        path: /boot
        state: remounted
        fstype: auto
        opts: rw
      when: realtime_kernel_grep_boot.rc == 0

    - name: Remove non-rt kernel and header packages
      ansible.builtin.apt:
        name: '{{ realtime_kernel_non_rt_kernels }}'
        state: absent
        autoremove: true
        purge: true
      when: realtime_kernel_non_rt_kernels | length > 0

    - name: Install realtime kernel
      ansible.builtin.apt:
        update_cache: true
        pkg: '{{ realtime_kernel_apt_packages }}'
      register: realtime_kernel_apt_install
