---
- name: Prepare the environment
  hosts: all
  become: true

  tasks:
    - name: Install base dependencies
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: true
