---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: example-test
    box: debian/bookworm64
    memory: 1024
    cpus: 1
    networks:
      - name: 'public_network'
        type: 'dhcp'
provisioner:
  name: ansible
  playbooks:
    converge: ../../voraus/ipc_tools/playbooks/example.yml
verifier:
  name: testinfra
  options:
    # https://github.com/pytest-dev/pytest-testinfra/issues/58#issuecomment-1839460327
    # pytest-ansible conflicts with --connection
    p: 'no:pytest-ansible'

    # avoid loading global pyproject.toml options, so we don't
    # load the setting that says "disable testinfra"
    c: '.'

    sudo: true # /boot/grub/grub.cfg is only readable by root
