---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: core-isolation-test
    box: generic/debian12
    memory: 1024
    cpus: 4
    networks:
      - name: 'public_network'
        type: 'dhcp'
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        role_name: voraus.ipc_tools.core_isolation
        core_isolation_isolated_core_ids: [1, 3]
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/converge.yml
verifier:
  name: testinfra
  options:
    # https://github.com/pytest-dev/pytest-testinfra/issues/58#issuecomment-1839460327
    # pytest-ansible conflicts with --connection
    p: 'no:pytest-ansible'

    # avoid loading global pyproject.toml options, so we don't
    # load the setting that says "disable testinfra"
    c: '.'

    sudo: true
