name: Docs

on: [workflow_call]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install tox
        run: python -m pip install --upgrade tox==4.23.2 tox-uv~=1.16.0

      - name: Build docs
        run: tox run -e docs

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/build/html/*
