name: Lint

on: [workflow_call]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install tox
        run: python -m pip install --upgrade tox==4.23.2 tox-uv~=1.16.0

      - name: Run static checks
        run: tox -e lint
